### ISSUE TITLE
fonts displays wrong on weather widget and firefox

### ISSUE THREAD

**Issue by x6ufeng** [Magisk-Modules-Alt-Repo/open_fonts#1]
![Screenshot_20220615-001440_One UI Home](https://user-images.githubusercontent.com/69743957/173626538-a034c9f1-c6d8-4fda-9253-38d8ea297f51.jpg)
![Screenshot_20220615-001446_Weather](https://user-images.githubusercontent.com/69743957/173626549-afb7d163-42c0-44ea-8a98-a82b81f3378a.jpg)
The positioning font is not displayed the way it should be on the weather widget. 
Letter in Firefox search bar are all displayed in capital.
The device is Samsung s20 with a snapdragon version.
Running on system based on oneui4.1

**Comment by F3FFO** [comment]
Hi @freddiehsu, i need to know some info:
1. module version
2. do you have changed emoji font?
3. you could share a screenshot of firefox? Because this issue I had solved

**Comment by x6ufeng** [comment]
> 

Module version is 1.1.3
I tried both with and without replacing the emoji, it just won't show.
Here are some examples on the Firefox bug

![Screenshot_20220617-234736_Firefox](https://user-images.githubusercontent.com/69743957/174333892-3e3b41e5-a482-4098-81f3-941478f7126c.jpg)
![Screenshot_20220617-235011_Firefox](https://user-images.githubusercontent.com/69743957/174333915-ed326bf5-e9df-4656-8f40-6c3d1c9e0305.jpg)

**Comment by F3FFO** [comment]
Thank you for your reply!🙏🏻 

> Here are some examples on the Firefox bug

I took a look at the font on firefox and noticed that it is not a browser problem but a search engine problem. I personally use DuckDuckGo on Firefox and this problem does not occur while on Google/Bing it does. I will investigate further!

> I tried both with and without replacing the emoji, it just won't show.

Regarding this I will have to investigate more because it seems like a thing related to certain specific apps

**Comment by F3FFO** [comment]
> I took a look at the font on firefox and noticed that it is not a browser problem but a search engine problem. I personally use DuckDuckGo on Firefox and this problem does not occur while on Google/Bing it does. I will investigate further!

After a series of attempts and tests I was able to understand the origin of the error. At the moment I still don't know how to fix it as it doesn't seem to be a problem related to the font but rather to the mix between font and Android system.

This is not to say that I give up but at the moment I would not know where to start. I share what little I have understood:
- In the font file.xml it is declared which font to use based on style (normal/italic) and weight; in particular the weight 400 and 500 are the main ones for the system (they use the Regular font).

  Of these two weights, the one responsible for the display of the font in the browser and in general in many applications is 400: `<font weight="400" style="normal">`

  It should be understood why the system interprets NotoSans as an all caps font


> Regarding this I will have to investigate more because it seems like a thing related to certain specific apps

I may have understood the reason for this error: initially I was going to replace the entire `fonts.xml` file, losing the custom fonts used by the producers. After the last commits I made, I'm going to modify the `fonts.xml` file during the boot phase(`post-fs-data.sh`), limiting the changes to only some parts of the file.

As soon as you can I would love if you could test the latest changes and tell me if anything has changed!🙏🏻
