### ISSUE TITLE
There is a mistake

### ISSUE THREAD

**Issue by HuskyDG** [Magisk-Modules-Alt-Repo/open_fonts#5]
WARNING: Do not symlink like this, normal apps cannot read font files:
```
ln -s $MODPATH/system/fonts/Roboto-Regular.ttf $MODPATH/system/fonts/Roboto-Thin.ttf
```
Use this instead:
```
ln -s /system/fonts/Roboto-Regular.ttf $MODPATH/system/fonts/Roboto-Thin.ttf
```

Or
```
ln -s ./Roboto-Regular.ttf $MODPATH/system/fonts/Roboto-Thin.ttf
```

**Comment by HuskyDG** [comment]
https://github.com/Magisk-Modules-Alt-Repo/open_fonts/blob/master/common/install.sh

**Comment by F3FFO** [comment]
Oh thank you so much for your feedback, I appreciate it so much.
I'll fix it right away!
