### ISSUE TITLE
Confusing Text (install_clock_font)

### ISSUE THREAD

**Issue by i8degrees** [Magisk-Modules-Alt-Repo/open_fonts#9]
@F3FFO Might you rework how the installation text shows when you choose not to replace the clock font? It feels misleading to me when reading it. Something like...

```shell
  if chooseport 3; then
    install_clock_font
  else
    ui_print "Android clock font not replaced."
  fi
  ui_print "  Fonts replaced!"
```

**Comment by F3FFO** [comment]
@i8degrees yes indeed you are right!

Feel free to open a PR with the changes you deem most appropriate and it will be my pleasure to check them and merge them as soon as they are ready!

**Comment by F3FFO** [comment]
Your proposal will be implemented in the next release

https://github.com/Magisk-Modules-Alt-Repo/open_fonts/commit/2e713400118a6a134bfdb17c3f4dadb9054dcf00
